travis:
  secure:
    BINSTAR_TOKEN: pRRFZJ/PRCyj9t0X01gISnpkv/3KP7oOLMKeilpd+4R8zm0FvDBg1ohi/PLftWArbukv3owVN/zLnA+grNN2q4AtxqNBBGFWOxGNsteNj5y8O5rntTnIYfkQtiSM4U9pa9e+puxmHJWI3DihsjeINilUJh8JWzUTnFIoRtcJq/zbaPnhY8Ux8iJCeFWobB0KGHYflTMoilyaDryU0kieZ8U7YhVlPyeFlIx0bJ+TBtqZRNpK/xFYOkCnlgJAlbROn90PlNUKWx1QCqtnpEgefhn8VNNwb1NihUurxrBm5rfg6WhOArVAWOkPvlBqjDaifNc1XkAMaSbK4lWK4tMhrYgApkF7KuoZYyuUwsiTAS7jOQw+KSqjrclklmfjQd1hzupkRj2Cql2sWDpVyOLgsqtPCUpxcS0UglY3oYeo1ZQlC9X5cfNwxkmxXid8Wptf1JVKc/C/WxYVcrFDPjUtdSYI4XYRX1a12cTlz/SXW3MpE/LlsJoEvgm2WocH28WBtNucn7P9crprQlpfxbw1XYkUYThb9v/o43LEBhzzC5iAOS/zaaq5F6U/wEmoVwCD2U/wWAtUSQJP+FawG1H8eH5oXoxfrxI7oA0cZ3Zr24oThfU0TZJRD2uplB3aY+NRZevYB8d1InvZpJmNPTNX0UO5cYvnirC0goVT4SIwntk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
